### PR TITLE
Added wd customizer option for adding custom wd methods.

### PR DESCRIPTION
**Pull request by nicovalencia**
Adds functionality for: https://github.com/wookiehangover/grunt-mocha-selenium/issues/9

I'm open to any ideas on making this cleaner, and would be happy to implement. I needed this functionality for a current project, so it's coming in hot out of my node_mods dir!

:hamburger:

### CODE REVIEW

**Comment by ifiokjr** [comment]
@nicovalencia I was just about to look into this and then I saw your pull request. Huge thanks!

@wookiehangover  is there any timescale on this being accepted or are there reasons for leaving it out?

**Comment by nicovalencia** [comment]
You bet, just pull from my fork for now. @wookiehangover has been busy, I'll nudge him in a bit.

**Comment by ifiokjr** [comment]
Will do.

**Comment by mhuggins** [comment]
@wookiehangover Any chance of getting a new version published to npm with this change? :)

**Pull request merged**
