### PR TITLE
Support PhantomJs + newer Selenium, add more flexible browser selection

### PR DESCRIPTION
**Pull request by drd**
There was a change in the selenium protocol which required a bump of wd, and instead of options.useChrome there is now options.browserName.

### CODE REVIEW

**Comment by drd** [comment]
Oops, I'll add another commit later, this just makes it possible to run phantom without actually providing a mechanism to do so.

**Comment by wookiehangover** [comment]
Would it be possible to make phantomjs a dependency (and [run it](https://github.com/Obvious/phantomjs#running-via-node) with [webdriver support](https://github.com/jmreidy/grunt-mocha-webdriver#using-grunt-mocha-webdriver-with-phantomjs)) so that this will work without having to run any other commands?

**Comment by drd** [comment]
I am a little undecided on whether we should always use the phantomjs installed by npm, use phantomjs from PATH as is currently implemented, or make a config option. Thoughts?

**Comment by drd** [comment]
or it may just be a lot simpler to spawn phantomjs with the correct port after selenium launches, as you suggested :)

**Comment by wookiehangover** [comment]
So there are a couple of benefits to including and npm-installed phantom.js:
- guaranteed version to test against
- completely isolated, removing the module removes all traces of selenium, chromedriver and phantom

And the downsides:
- larger npm payload
- phantomjs may be installed but never used

My vote is to include it as an dependency with NPM, but I'd be open to suggestion if there are better ways of getting it downloaded for the correct platform dynamically.

**Comment by drd** [comment]
Do you have an opinion on whether to let selenium manage the phantomjs process by adding phantom to the path or explicitly launching phantom once we have the selenium port?

**Comment by drd** [comment]
I decided to rip out all the process launching code, and just let things fail if they are going to — also, I agree that depending on npm phantom by default is correct.

**Comment by wookiehangover** [comment]
I'm going to test this out today with the intention of getting it merged. Thanks @drd for the patience and work to make this feature happen!

**Pull request merged**
